name: Setup Niar

inputs:
  install-oss-cad-suite:
    description: Install OSS CAD Suite.

  github-token:
    description: GitHub token used by YosysHQ/setup-oss-cad-suite.

  install-zig:
    description: Install Zig with specified version.

runs:
  using: composite
  steps:
  - name: Setup PDM
    uses: pdm-project/setup-pdm@v4

  - name: Install Python dependencies
    run: pdm install
    shell: bash

  - name: Install OSS CAD Suite
    if: ${{ inputs.install-oss-cad-suite }}
    uses: YosysHQ/setup-oss-cad-suite@v3
    with:
      github-token: ${{ inputs.github-token }}

  - name: Report Yosys version
    if: ${{ inputs.install-oss-cad-suite }}
    run: yosys --version
    shell: bash

  - name: Install Zig
    if: ${{ inputs.install-zig }}
    uses: goto-bus-stop/setup-zig@v2
    with:
      version: ${{ inputs.install-zig }}

  - name: Report Zig version
    if: ${{ inputs.install-zig }}
    run: zig version
    shell: bash
